server:
  port: 5010
  
spring:
  application:
    name: zuul-api-gateway-service1 
  main:
    web-application-type: none

eureka:
  instance:
    hostname: localhost
    
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:5007/eureka
    eureka-server-port: 5007

zuul:
  host:
    socket-timeout-millis: 500000
    connect-timeout-millis: 500000
  
  ignored-services:
  - '*'
  
  routes:
    resource:
      path: /resouce/**
      service-id: eureka-client-resouce_mapping-service
      strip-prefix: true
    
    user:
      path: /user/**
      service-id: eureka-client-service1
      strip-prefix: true
      
         
#zuul:
#  host:
#    connect-timeout-millis: 5000000
#    socket-timeout-millis: 5000000
#  ignored-services: '*'
#  routes:
#    resource-service: # custom(prashath/user/...) key/name
#      path: /resouce/**
#      service-id: eureka-client-resouce_mapping-service
#      strip-prefix: true
#    user-service: # custom(prashath/user/...) key/name
#      path: /user/**
#      service-id: eureka-client-service1
#      strip-prefix: true